### PR TITLE
Fix Centered Content Switcher issue

### LINKED ISSUE #93: Implement centered-content-switcher block
Original: https://www.esri.com/en-us/about/about-esri/americas

Suggestion: a similar structure to "mosaic reveal" block might be a good idea

image

### PR DESCRIPTION
**Pull request by vladciocoiu**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #93 

Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/americas
- Before: https://main--esri--aemsites.hlx.live/en-us/about/about-esri/americas
- After: https://fix-centered-content-switcher--esri--aemsites.hlx.live/en-us/about/about-esri/americas

### CODE REVIEW

File: blocks/centered-content-switcher/centered-content-switcher.js [hunk 1]
```diff
@@ -60,7 +60,9 @@ export default function decorate(block) {
     ul(
       { class: 'desktop-nav-list' },
       ...[...block.children].map((child, idx) => {
-        const thumbnailUrl = child.children[0].children[2].querySelector('img').src;
+        const thumbnailUrl = child.children[0].children[3].querySelector('img').src;
```
Comment (alexcarol) [inline blocks/centered-content-switcher/centered-content-switcher.js:63]: Rather than selecting the url, can you grab the whole "picture" element? The idea is that it's optimised for each screen size.

Comment (alexcarol) [inline blocks/centered-content-switcher/centered-content-switcher.js:63]: As the picture/img is always the first one within the div, why not just select child.children[0].querySelector('picture')? Then if you place it elsewhere you don't need to worry about removing it (or the parent picture).

**Review by alexcarol — APPROVED** [review]
